name: snyk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Templates.sln

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test
        shell: pwsh
        run: |
          $projects = @(
            'src/Community.PowerToys.Run.Plugin.Templates.csproj'
            'tests/Community.PowerToys.Run.Plugin.Templates.Tests.csproj'
          )

          foreach ($project in $projects) {
            snyk test --file=$project --package-manager=nuget
          }

      - name: Monitor
        shell: pwsh
        run: |
          $projects = @(
            'src/Community.PowerToys.Run.Plugin.Templates.csproj'
            'tests/Community.PowerToys.Run.Plugin.Templates.Tests.csproj'
          )

          foreach ($project in $projects) {
            snyk monitor --file=$project --package-manager=nuget
          }
